apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE
      description: "Image name including registry (e.g., gcr.io/my-project/my-image:latest)"
  steps:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=/workspace/source/ci-cd-final-project/Dockerfile"
        - "--context=/workspace/source/ci-cd-final-project"
        - "--destination=$(params.IMAGE)"
        - "--insecure"
